#!/bin/zsh
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OWNER_ENV_FILE="${FLASHARB_OWNER_ENV_FILE:-/Users/yanqing/Documents/GitHub/miraix-interface/projects/xlayer-agent-fight-club/.env.local}"

if [[ ! -f "$OWNER_ENV_FILE" ]]; then
  echo "Owner env file not found: $OWNER_ENV_FILE" >&2
  exit 1
fi

cd "$ROOT_DIR"
export PATH="$HOME/.local/bin:$PATH"

set -a
source "$OWNER_ENV_FILE"
set +a

export ONCHAINOS_PROXY="${ONCHAINOS_PROXY:-${OKX_AGENT_PROXY:-http://127.0.0.1:7890}}"
export WALLET_ADDRESS="${WALLET_ADDRESS:-0xdbc8e35ea466f85d57c0cc1517a81199b8549f04}"
export FLASHARB_EXECUTION_BACKEND="${FLASHARB_EXECUTION_BACKEND:-agentic}"
export FLASHARB_BASE_TOKEN="${FLASHARB_BASE_TOKEN:-auto}"
export FLASHARB_BASE_TOKENS="${FLASHARB_BASE_TOKENS:-USDT0,USDC,USDT}"
export FLASHARB_TOKENS="${FLASHARB_TOKENS:-OKB}"
export FLASHARB_DEXES="${FLASHARB_DEXES:-uniswap,quickswap}"
export CHECK_INTERVAL="${CHECK_INTERVAL:-300}"
export MOLTBOOK_POST_INTERVAL="${MOLTBOOK_POST_INTERVAL:-600}"
export FLASHARB_IDLE_PROBE_ENABLED="${FLASHARB_IDLE_PROBE_ENABLED:-true}"
export FLASHARB_IDLE_PROBE_TOKEN="${FLASHARB_IDLE_PROBE_TOKEN:-OKB}"
export FLASHARB_IDLE_PROBE_AMOUNT_USD="${FLASHARB_IDLE_PROBE_AMOUNT_USD:-0.10}"
export FLASHARB_IDLE_PROBE_INTERVAL="${FLASHARB_IDLE_PROBE_INTERVAL:-600}"
export FLASHARB_RATE_LIMIT_COOLDOWN_SEC="${FLASHARB_RATE_LIMIT_COOLDOWN_SEC:-180}"
export FLASHARB_AGENTIC_ORDER_RETRY_COUNT="${FLASHARB_AGENTIC_ORDER_RETRY_COUNT:-6}"
export FLASHARB_AGENTIC_ORDER_RETRY_DELAY_SEC="${FLASHARB_AGENTIC_ORDER_RETRY_DELAY_SEC:-8}"

exec python3 -u run.py --live
